version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "gdal"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
