version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 50
  allow:
    - dependency-type: direct
    - dependency-type: indirect
    ignore:
    - dependency-name: "gdal"
      versions: [">3.6.2"]
      